import Image from "next/image";
import Link from "next/link";
import Head from "next/head";
import meli from "../public/images/logo__large_plus.png";
import Searchbar from "./searchbar";
import Breadcrumb from "./beadcrumb";
const Layout = ({
  children,
}: {
  children: React.ReactNode;
  home?: boolean;
}) => {
  return (
    <div>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav
        className="navbar is-align-items-center is-justify-content-center"
        role="navigation"
        aria-label="main navigation"
      >
        <div className="container columns is-mobile is-vcentered">
          <div className="column">
            <Link href="/">
              <a className="navbar-item">
                <Image src={meli} alt="Picture" width={112} height={28} />
              </a>
            </Link>
          </div>
          <div className="column is-10">
            <Searchbar />
          </div>
        </div>
      </nav>
      <div className="background">
        <div className="container">
          <Breadcrumb />
          <div className="body">{children}</div>
        </div>
      </div>
    </div>
  );
};

export default Layout;
